USE twitterdb;
CREATE TABLE tweets (
	ID INT(11) NOT NULL AUTO_INCREMENT,
    username VARCHAR(225) DEFAULT NULL,
    created_at VARCHAR(45) DEFAULT NULL,
    tweet TEXT DEFAULT NULL,
    retweet_count INT(11) DEFAULT NULL,
    location VARCHAR(100) DEFAULT NULL,
    place VARCHAR(100) DEFAULT NULL,
PRIMARY KEY(ID)
);